name: GitHub Actions Deploy to unit
on: [push]
jobs:
  Deploy-to-Unit:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          UNIT_SERVER: ${{ secrets.UNIT_SERVER }}
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          curl -X POST http://52.63.250.232:8080/pull -d '{ "branch":"main", "dest":"/www/pacman-unit", "repo":"http://github.com/${{ github.repository }}" }'
          echo "curl -s -X POST http://x.x.x.x:8080/pull -d ${{ github.repository }}" > /tmp/foo
      #- run: cat /tmp/foo
      #- name: Check out repository code
      #  uses: actions/checkout@v2
      #- run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      #- run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      #- name: List files in the repository
      #  run: |
      #    ls ${{ github.workspace }}
      #- run: echo "ğŸ This job's status is ${{ job.status }}."
